using System;
using System.Collections.Generic;

namespace ProjectEuler100.Problems
{
    // How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
    // Solution time = 00:00:00.0098156
    public class Problem029
    {
        public int Solve(int aBound, int bBound)
        {
            return GetNumDistinctTerms(aBound, bBound);
        }

        // We don't care about overflows as we don't need actual answers, just distinct terms
        private int GetNumDistinctTerms(int aBound, int bBound)
        {
            var set = new HashSet<double>();

            for (int a = 2; a <= aBound; a++)
            {
                for (int b = 2; b <= bBound; b++)
                {
                    set.Add(Math.Pow(a, b));
                }
            }

            return set.Count;
        }
    }
}
